# Generated by Django 4.1.3 on 2022-11-03 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_total', models.IntegerField(default=0)),
                ('status', models.CharField(default='E', max_length=1)),
            ],
            options={
                'db_table': 'accountbooks',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('month_total', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'calendars',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('money_type', models.CharField(choices=[('income', 'Income'), ('pay', 'Pay')], max_length=6)),
                ('detail_type', models.CharField(default='E', max_length=1)),
                ('money', models.IntegerField()),
                ('memo', models.TextField(null=True)),
                ('status', models.CharField(default='E', max_length=1)),
                ('accountbook', models.ForeignKey(db_column='accountbook_id', on_delete=django.db.models.deletion.CASCADE, to='accountbook.accountbook')),
            ],
            options={
                'db_table': 'moneys',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='accountbook',
            name='calendar',
            field=models.OneToOneField(db_column='calendar_id', on_delete=django.db.models.deletion.CASCADE, to='accountbook.calendar'),
        ),
        migrations.AddField(
            model_name='accountbook',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
