# Generated by Django 4.1.3 on 2022-11-04 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_user_plan_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField()),
                ('day_total', models.IntegerField(default=0)),
                ('delete_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'accountbooks',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('money', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('memo', models.TextField(null=True)),
                ('delete_status', models.BooleanField(default=False)),
                ('accountbook', models.ForeignKey(db_column='accountbook_id', on_delete=django.db.models.deletion.CASCADE, to='accountbook.accountbook')),
            ],
            options={
                'db_table': 'pays',
                'abstract': False,
                'managed': True,
            },
        ),
    ]
